volumes:
  grafana:
  postgres:

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  grafana:
    image: grafana/grafana:10.4.0
    environment:
      GF_DATABASE_TYPE: postgres
      GF_DATABASE_HOST: postgres:5432
      GF_DATABASE_NAME: postgres
      GF_DATABASE_USER: postgres
      GF_DATABASE_PASSWORD: postgres
      GF_LOG_LEVEL: debug
      GF_ALERTING_ENABLED: false
      GF_UNIFIED_ALERTING_EXECUTE_ALERTS: false
      GF_ALERTING_EXECUTE_ALERTS: false
    volumes:
      - grafana:/var/lib/grafana
    depends_on:
      - postgres
    ports:
      - "3300:3000"
