apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "teams-backend.fullname" . }}
  labels:
    {{- include "teams-backend.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "teams-backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "teams-backend.selectorLabels" . | nindent 8 }}
      annotations:
        kubectl.kubernetes.io/default-container: {{ .Chart.Name }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
      serviceAccountName: {{ include "teams-backend.fullname" . }}
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ include "teams-backend.fullname" . }}
                optional: true
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          env:
            # General
            - name: LOG_FORMAT
              value: {{ .Values.logFormat }}
            - name: LOG_LEVEL
              value: {{ .Values.logLevel }}
            - name: INSECURE_GRPC
              value: {{ .Values.nais_api.insecure }}
            - name: GRPC_TARGET
              value: {{ .Values.nais_api.url }}
            - name: LISTEN_ADDRESS
              value: :3005
            - name: TENANT_DOMAIN
              value: {{ .Values.tenantDomain }}
            - name: TENANT_NAME
              value: {{ .Values.tenantName }}
            # GitHub
            - name: GITHUB_AUTH_ENDPOINT
              value: {{ .Values.gitHub.authEndpoint }}
            - name: GITHUB_ORG
              value: {{ .Values.gitHub.organization }}

          ports:
            - name: http
              containerPort: 3005
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
