apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "api-reconcilers.fullname" . }}
  labels:
    {{- include "api-reconcilers.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "api-reconcilers.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "api-reconcilers.selectorLabels" . | nindent 8 }}
      annotations:
        kubectl.kubernetes.io/default-container: {{ .Chart.Name }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
      serviceAccountName: {{ include "api-reconcilers.fullname" . }}
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ include "api-reconcilers.fullname" . }}
                optional: true
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          env:
            # General
            - name: LOG_FORMAT
              value: {{ .Values.logFormat }}
            - name: LOG_LEVEL
              value: {{ .Values.logLevel }}
            - name: INSECURE_GRPC
              value: {{ .Values.naisAPI.insecure | quote }}
            - name: GRPC_TARGET
              value: {{ .Values.naisAPI.target }}
            - name: LISTEN_ADDRESS
              value: :3005
            - name: CLUSTER_ALIAS
              value: {{ .Values.clusterAlias | join "," | quote }}
            - name: TENANT_DOMAIN
              value: {{ .Values.tenantDomain }}
            - name: TENANT_NAME
              value: {{ .Values.fasit.tenant.name }}
            - name: RECONCILERS_TO_ENABLE
              value: {{ .Values.reconcilersToEnable | quote }}
            - name: GOOGLE_MANAGEMENT_PROJECT_ID
              value: {{ .Values.googleManagementProjectID | quote }}
            # GitHub
            - name: GITHUB_AUTH_ENDPOINT
              value: {{ .Values.gitHub.authEndpoint }}
            - name: GITHUB_ORG
              value: {{ .Values.gitHub.organization }}
            # Grafana
            - name: GRAFANA_ENDPOINT
              value: {{ .Values.grafana.endpoint }}
            - name: GRAFANA_USERNAME
              value: {{ .Values.grafana.username }}
            # Azure
            {{- if .Values.azure.groupNamePrefix }}
            - name: AZURE_GROUP_NAME_PREFIX
              value: {{ .Values.azure.groupNamePrefix }}
            {{- end }}
            # NAIS deploy
            - name: NAIS_DEPLOY_ENDPOINT
              value: {{ .Values.naisDeploy.endpoint }}
            # GCP
            - name: GCP_BILLING_ACCOUNT
              value: {{ .Values.gcp.billingAccount | quote }}
            - name: GCP_CLUSTERS
              value: {{ .Values.gcp.clusters | quote }}
            - name: GCP_WORKLOAD_IDENTITY_POOL_NAME
              value: {{ .Values.gcp.workloadIdentityPoolName | quote }}
            - name: GCP_SERVICE_ACCOUNT_EMAIL
              value: {{ .Values.serviceAccount.email | quote }}
            # DependencyTrack
            - name: DEPENDENCYTRACK_ENDPOINT
              value: {{ .Values.dependencyTrack.endpoint | quote }}
            - name: DEPENDENCYTRACK_USERNAME
              value: {{ .Values.dependencyTrack.username | quote }}
            # Google
            - name: GOOGLE_ADMIN_SERVICE_ACCOUNT_EMAIL
              value: {{ .Values.google.adminServiceAccountEmail | default (printf "tenant-directory-sa@%s.iam.gserviceaccount.com" .Values.googleManagementProjectID) | quote }}
            - name: GOOGLE_ADMIN_USER_EMAIL
              value: {{ .Values.google.adminUserEmail | default (printf "nais-admin@%s" .Values.tenantDomain) | quote }}
            # Feature flags
            {{- if .Values.featureFlags.attachSharedVpc }}
            - name: FEATURE_ATTACH_SHARED_VPC
              value: {{ .Values.featureFlags.attachSharedVpc | quote }}
            {{- end }}
            {{- if .Values.kubernetes.static }}
            - name: NAV_ONPREM_CLUSTERS
              value: {{ .Values.kubernetes.static | quote }}
            {{- end }}
          ports:
            - name: http
              containerPort: 3005
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
