apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "api-reconcilers.fullname" . }}
  labels:
    {{- include "api-reconcilers.labels" . | nindent 4 }}
spec:
  endpoints:
  - interval: 1m
    port: http
    scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "api-reconcilers.selectorLabels" . | nindent 6 }}
