apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "api-reconcilers.fullname" . }}
  labels:
    {{- include "api-reconcilers.labels" . | nindent 4 }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.google.serviceAccountEmail }}
