apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-reconciler
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: api-reconciler-role
rules:
  - apiGroups: [ "" ]
    resources: [ "namespaces" ]
    verbs: [ "get", "create", "update", "delete" ]
  - apiGroups: [ "" ]
    resources: [ "resourcequotas" ]
    verbs: [ "get", "create" ]
  - apiGroups: [ "" ]
    resources: [ "serviceaccounts" ]
    verbs: [ "get" , "create" ]
  - apiGroups: [ "rbac.authorization.k8s.io" ]
    resources: [ "rolebindings" ]
    verbs: [ "get", "create", "update" ]
  - apiGroups: [ "core.cnrm.cloud.google.com" ]
    resources: [ "configconnectorcontexts" ]
    verbs: [ "get", "create", "update" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: api-reconciler-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: api-reconciler-role
subjects:
  - kind: ServiceAccount
    name: api-reconciler
    namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nais:developer
rules:
  - apiGroups: [ "" ]
    resources: [ "namespaces" ]
    verbs: [ "get" ]