environmentKinds:
  - management

dependencies:
  - allOf:
      - nais-api

values:
  resources.requests.cpu:
    displayName: CPU request
    config:
      type: string

  resources.requests.memory:
    displayName: Memory request
    config:
      type: string

  googleManagementProjectID:
    displayName: Google management project ID
    computed:
      template: |
        {{ .Env.project_id | quote }}

  tenantDomain:
    displayName: Tenant domain
    computed:
      template: |
        {{ .Env.tenant_domain | quote }}

  reconcilersToEnable:
    displayName: Reconcilers to enable
    description: Comma separated list of reconcilers to enable. Changing this value after the reconciler has been registered will not have any effect.
    config:
      type: string

  azure.groupNamePrefix:
    displayName: Azure group name prefix
    config:
      type: string

  gitHub.authEndpoint:
    displayName: GitHub auth endpoint
    description: The endpoint for the token service that provisions teams-backend with GitHub installation tokens for the correct tenant organization.
    computed:
      template: |
        {{ .Env.teams_github_auth_endpoint | quote }}

  gitHub.organization:
    displayName: GitHub organization
    description: The organization slug where the github reconciler will manage teams
    computed:
      template: |
        {{ .Env.teams_github_org | quote }}

  naisDeploy.provisionKey:
    displayName: NAIS deploy provision key
    computed:
      template: |
        {{ .Env.hookd_provision_key | quote }}

  google.serviceAccountEmail:
    displayName: Google service account email
    computed:
      template: |
        {{ .Env.teams_google_service_account_email | quote }}

  gcp.billingAccount:
    displayName: Billing account
    computed:
      template: '{{ .Env.billing_account | quote }}'

  gcp.clusters:
    displayName: Cluster information
    computed:
      template: |
        {{ if (eq .Tenant.Name "nav") }}
        {{ filter "kind" "legacy" .Envs | environmentsAsMap "teams_folder_id,project_id" | toJSON | quote }}
        {{ else }}
        {{ filter "kind" "tenant" .Envs | environmentsAsMap "teams_folder_id,project_id" | toJSON | quote }}
        {{ end }}

  gcp.cnrmRole:
    displayName: CNRM role string
    computed:
      template: '"organizations/{{ .Env.org_id }}/roles/{{ .Env.cnrm_role }}"'

  gcp.workloadIdentityPoolName:
    displayName: Google workload identity pool name
    computed:
      template: '{{ .Env.nais_identity_pool_name | quote }}'

  dependencytrack.password:
    displayName: DependencyTrack password
    computed:
      template: "{{ .Env.teams_dependencytrack_password | quote }}"
