environmentKinds:
  - management

dependencies:
  - allOf:
      - nais-api

values:
  resources.requests.cpu:
    displayName: CPU request
    config:
      type: string

  resources.requests.memory:
    displayName: Memory request
    config:
      type: string

  featureFlags.attachSharedVpc:
    displayName: Attach Shared VPC
    config:
      type: bool

  featureFlags.enableGrafanaAlerts:
    displayName: Enable Grafana Alerts
    config:
      type: bool

  googleManagementProjectID:
    displayName: Google management project ID
    computed:
      template: |
        {{ .Env.project_id | quote }}

  tenantDomain:
    displayName: Tenant domain
    computed:
      template: |
        {{ .Env.tenant_domain | quote }}

  clusterAlias:
    displayName: Cluster aliases
    description: Each entry must be colon separeted key:value cluster aliases (e.g. dev:dev-gcp)
    config:
      type: string_array

  reconcilersToEnable:
    displayName: Reconcilers to enable
    description: Comma separated list of reconcilers to enable. Changing this value after the reconciler has been registered will not have any effect.
    config:
      type: string

  azure.groupNamePrefix:
    displayName: Azure group name prefix
    config:
      type: string

  gitHub.authEndpoint:
    displayName: GitHub auth endpoint
    description: The endpoint for the token service that provisions GitHub installation tokens for the correct tenant organization.
    computed:
      template: |
        {{ .Env.teams_github_auth_endpoint | quote }}

  gitHub.organization:
    displayName: GitHub organization
    description: The organization slug where the github reconciler will manage teams
    computed:
      template: |
        {{ .Env.teams_github_org | quote }}

  naisDeploy.provisionKey:
    displayName: NAIS deploy provision key
    computed:
      template: |
        {{ .Env.hookd_provision_key | quote }}

  serviceAccount.email:
    displayName: Email address of the GCP service account
    description: The email address of the service account that is used when using the Google APIs
    computed:
      template: |
        {{ .Env.nais_api_reconcilers_serviceaccount_email | quote }}

  google.adminServiceAccountEmail:
    displayName: Email address of the Google Workspace Admin service account
    description: The email address of the service account that is used when using the Google Workspace Admin APIs
    config:
      type: string

  google.adminUserEmail:
    displayName: Email address of the admin user for Google Workspace
    description: The email address of the user that is impersonated when using the Google Workspace Admin APIs
    config:
      type: string

  gcp.billingAccount:
    displayName: Billing account
    computed:
      template: "{{ .Env.billing_account | quote }}"

  kubernetes.static:
    displayName: Static Kubernetes clusters
    description: Comma-separated list of clusters with static credentials on the format 'name|apiserverHost|token'
    config:
      type: string
      secret: true

  kubernetes.clusters:
    displayName: GKE clusters
    description: Comma-separated list of static resources to monitor
    config:
      type: string
    computed:
      template: |
        {{- $tenantEnvs := filter "kind" "tenant" .Envs -}}
        {{ eachOf $tenantEnvs "name" | sortAlpha | join "," }}

  gcp.clusters:
    displayName: Cluster information
    computed:
      template: |
        {{ filter "kind" "tenant" .Envs | environmentsAsMap "teams_folder_id,project_id" | toJSON | quote }}
    config:
      type: string

  gcp.workloadIdentityPoolName:
    displayName: Google workload identity pool name
    computed:
      template: "{{ .Env.nais_identity_pool_name | quote }}"

  grafana.endpoint:
    displayName: Grafana API endpoint
    config:
      type: string

  grafana.username:
    displayName: Grafana admin username
    config:
      type: string

  grafana.password:
    displayName: Grafana admin password
    computed:
      template: "{{ .Env.grafana_admin_password | quote }}"

  grafana.slackWebhookURL:
    displayName: Grafana Slack webhook URL
    description: The Slack webhook URL for sending alert notifications
    config:
      type: string

  dependencyTrack.password:
    displayName: DependencyTrack password
    computed:
      template: "{{ .Env.teams_dependencytrack_password | quote }}"

  image.tag:
    displayName: Image tag
    config:
      type: string

  loglevel:
    displayName: Log level
    config:
      type: string